version: '3.8'

services:
  app:
    build: .
    container_name: avoxi_go_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: avoxi
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: avoxi
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: