// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: internal/grpc/ipcheck.proto

package ipcheckpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IpChecker_CheckIP_FullMethodName = "/ipcheckpb.IpChecker/CheckIP"
)

// IpCheckerClient is the client API for IpChecker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IpCheckerClient interface {
	CheckIP(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
}

type ipCheckerClient struct {
	cc grpc.ClientConnInterface
}

func NewIpCheckerClient(cc grpc.ClientConnInterface) IpCheckerClient {
	return &ipCheckerClient{cc}
}

func (c *ipCheckerClient) CheckIP(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, IpChecker_CheckIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IpCheckerServer is the server API for IpChecker service.
// All implementations must embed UnimplementedIpCheckerServer
// for forward compatibility.
type IpCheckerServer interface {
	CheckIP(context.Context, *CheckRequest) (*CheckResponse, error)
	mustEmbedUnimplementedIpCheckerServer()
}

// UnimplementedIpCheckerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIpCheckerServer struct{}

func (UnimplementedIpCheckerServer) CheckIP(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckIP not implemented")
}
func (UnimplementedIpCheckerServer) mustEmbedUnimplementedIpCheckerServer() {}
func (UnimplementedIpCheckerServer) testEmbeddedByValue()                   {}

// UnsafeIpCheckerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IpCheckerServer will
// result in compilation errors.
type UnsafeIpCheckerServer interface {
	mustEmbedUnimplementedIpCheckerServer()
}

func RegisterIpCheckerServer(s grpc.ServiceRegistrar, srv IpCheckerServer) {
	// If the following call pancis, it indicates UnimplementedIpCheckerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IpChecker_ServiceDesc, srv)
}

func _IpChecker_CheckIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpCheckerServer).CheckIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IpChecker_CheckIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpCheckerServer).CheckIP(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IpChecker_ServiceDesc is the grpc.ServiceDesc for IpChecker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IpChecker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ipcheckpb.IpChecker",
	HandlerType: (*IpCheckerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckIP",
			Handler:    _IpChecker_CheckIP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/grpc/ipcheck.proto",
}
